-- ClothesStyle 衣服款式
delete from `t_tool_generate_rule` where `f_code` = 'ClothesStyle';
insert into `t_tool_generate_rule` (`f_id`, `f_code`, `f_name`, `f_menu_id`, `f_menu_name`, `f_menu_remark`, `f_menu_parent_id`, `f_menu_parent_path`, `f_menu_order`, `f_request_url`, `f_package_name`) values('3','ClothesStyle','衣服款式','DIY-HZHB-YFKS','衣服款式管理','衣服款式管理页面','DIY-HZHB','/ROOT/DIY-HZHB/','120','/api/diy/partner/clothes/styles','com.jeeweb.diy.partner');

-- t_diy_clothes_style
delete from `t_tool_generate_rule_table` where `f_rule_id` = '3' and `f_db_name` = 'jeeweb-diy' and `f_table_name` = 't_diy_clothes_style';
insert into `t_tool_generate_rule_table` (`f_id`, `f_rule_id`, `f_db_name`, `f_table_name`, `f_order`, `f_is_main`, `f_entity_interface`, `f_entity_base_class`, `f_entity_class`, `f_mapper_base_class`, `f_mapper_class`, `f_service_base_class`, `f_service_class`, `f_rest_base_class`, `f_rest_class`) values('3','3','jeeweb-diy','t_diy_clothes_style','1','101','com.jeeweb.framework.business.model.ICreator','com.jeeweb.framework.business.entity.BaseEntity','com.jeeweb.diy.partner.entity.ClothesStyleEntity','com.jeeweb.framework.business.mapper.BaseMapper','com.jeeweb.diy.partner.mapper.ClothesStyleMapper','com.jeeweb.framework.business.service.BaseService','com.jeeweb.diy.partner.service.ClothesStyleService','com.jeeweb.framework.business.web.api.BaseApi','com.jeeweb.diy.partner.web.api.ClothesStyleApi');

delete from `t_tool_generate_rule_field` where `f_table_id` = '3';
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('15','3','0','f_id','ID','bigint(20)','java.lang.Long','101','101','102','102','102','101','102','102','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('16','3','1','f_partner_id','关联合作伙伴ID','bigint(20)','java.lang.Long','102','102','102','101','101','101','101','102','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('17','3','2','f_code','款式编号','varchar(50)','java.lang.String','102','102','102','101','101','101','101','101','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('18','3','3','f_name','款式名称','varchar(80)','java.lang.String','102','102','102','101','101','101','102','101','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('19','3','4','f_desc','描述','text','java.lang.String','102','102','102','101','101','101','102','102','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('20','3','5','f_cost_price','成本价，单位元，如果尺码有成本价以尺码的成本价算尺码优先','decimal(13,2)','java.math.BigDecimal','102','102','102','101','101','101','102','102','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('21','3','6','f_crowd_type','款式人群类型：101、通款(不分男女)；102、通款+童装；103、分款(男款女款)；104、分款+童装；105、童装','tinyint(3) unsigned','java.lang.Integer','102','102','102','101','101','101','101','102','102','102','101','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('22','3','7','f_weight','重量，单位g(克)，用于计算运费','int(11)','java.lang.Integer','102','102','102','101','101','101','102','102','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('23','3','8','f_creator_id','创建人ID','bigint(20)','java.lang.Long','102','102','101','101','102','101','101','102','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('24','3','9','f_creator_name','创建人姓名','varchar','java.lang.String','102','102','101','102','102','102','102','101','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('25','3','10','f_created_time','创建时间','datetime','java.sql.Timestamp','102','102','101','101','102','101','102','102','102','102','102','102','101','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('26','3','11','f_status','状态：101、出售；102、停售','tinyint(3) unsigned','java.lang.Integer','102','102','102','101','101','101','101','102','102','102','101','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('27','3','12','f_remark','备注','longtext','java.lang.String','102','102','102','101','101','101','102','102','102','102','102','102','102','102','102','102');
