-- ClothesSize 衣服尺码
delete from `t_tool_generate_rule` where `f_code` = 'ClothesSize';
insert into `t_tool_generate_rule` (`f_id`, `f_code`, `f_name`, `f_menu_id`, `f_menu_name`, `f_menu_remark`, `f_menu_parent_id`, `f_menu_parent_path`, `f_menu_order`, `f_request_url`, `f_package_name`) values('2','ClothesSize','衣服尺码','DIY-HZHB-YFCM','衣服尺码管理','衣服尺码管理页面','DIY-HZHB','/ROOT/DIY-HZHB/','100','/api/diy/partner/clothes/sizes','com.jeeweb.diy.partner');

-- t_diy_clothes_size
delete from `t_tool_generate_rule_table` where `f_rule_id` = '2' and `f_db_name` = 'jeeweb-diy' and `f_table_name` = 't_diy_clothes_size';
insert into `t_tool_generate_rule_table` (`f_id`, `f_rule_id`, `f_db_name`, `f_table_name`, `f_order`, `f_is_main`, `f_entity_interface`, `f_entity_base_class`, `f_entity_class`, `f_mapper_base_class`, `f_mapper_class`, `f_service_base_class`, `f_service_class`, `f_rest_base_class`, `f_rest_class`) values('2','2','jeeweb-diy','t_diy_clothes_size','1','101','null','com.jeeweb.framework.business.entity.BaseEntity','com.jeeweb.diy.partner.entity.ClothesSizeEntity','com.jeeweb.framework.business.mapper.BaseMapper','com.jeeweb.diy.partner.mapper.ClothesSizeMapper','com.jeeweb.framework.business.service.BaseService','com.jeeweb.diy.partner.service.ClothesSizeService','com.jeeweb.framework.business.web.api.BaseApi','com.jeeweb.diy.partner.web.api.ClothesSizeApi');

delete from `t_tool_generate_rule_field` where `f_table_id` = '2';
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('7','2','0','f_id','','bigint(20)','java.lang.Long','101','101','102','102','102','101','102','102','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('8','2','1','f_partner_id','关联合作伙伴ID','bigint(20)','java.lang.Long','102','102','102','101','101','101','101','102','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('9','2','2','f_type','类型：101、通用；102、男；103、女；104、童','tinyint(3) unsigned','java.lang.Integer','102','102','102','101','101','101','101','102','102','102','101','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('10','2','3','f_size','尺码：XS、S、M、L、XL、2XL、3XL、4XL、5XL、6XL、7XL、8XL','varchar(8)','java.lang.String','102','102','102','101','101','101','101','102','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('11','2','4','f_code','尺码编号，通：XS-A、S-A、M-A、L-A、XL-A、2XL-A、3XL-A、4XL-A、5XL-A、6XL-A、7XL-A；男：XS-M、S-M、M-M、L-M、XL-M、2XL-M、3XL-M、4XL-M、5XL-M、6XL-M、7XL-M；女：XS-W、S-W、M-W、L-W、XL-W、2XL-W、3XL-W、4XL-W、5XL-W、6XL-W、7XL-W、8XL-W；童：XS-Y、S-Y、M-Y、L-Y、XL-Y、2XL-Y、3XL-Y、4XL-Y','varchar(32)','java.lang.String','102','102','102','101','101','101','101','101','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('12','2','5','f_name','尺码名称','varchar(64)','java.lang.String','102','102','102','101','101','101','102','101','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('13','2','6','f_desc','描述','text','java.lang.String','102','102','102','101','101','101','102','102','102','102','102','102','102','102','102','102');
insert into `t_tool_generate_rule_field` (`f_id`, `f_table_id`, `f_order`, `f_column_name`, `f_column_comment`, `f_column_type`, `f_java_type`, `f_is_primary`, `f_is_super_class_field`, `f_is_override_field`, `f_is_insert`, `f_is_update`, `f_is_select`, `f_is_equal`, `f_is_like`, `f_is_left_like`, `f_is_right_like`, `f_is_in`, `f_is_not_in`, `f_is_between`, `f_is_search`, `f_is_grid`, `f_is_form`) values('14','2','7','f_remark','备注','longtext','java.lang.String','102','102','102','101','101','101','102','102','102','102','102','102','102','102','102','102');
